"""
report_generator.py — PDF & Export Report Generator
AI Data Analyst Assistant

Generates professional PDF reports with ReportLab and data exports.
"""

import io
import os
from datetime import datetime
from pathlib import Path
from typing import Optional

import pandas as pd
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4, letter
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch, cm
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle,
    HRFlowable, PageBreak
)
from reportlab.platypus import Image as RLImage
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT

from config import REPORTS_DIR


# ──────────────────────────────────────────
# Style Definitions
# ──────────────────────────────────────────
def _get_styles():
    styles = getSampleStyleSheet()

    styles.add(ParagraphStyle(
        name="AppTitle",
        fontSize=28, fontName="Helvetica-Bold",
        textColor=colors.HexColor("#667eea"),
        spaceAfter=6, alignment=TA_CENTER,
    ))
    styles.add(ParagraphStyle(
        name="SubTitle",
        fontSize=13, fontName="Helvetica",
        textColor=colors.HexColor("#8892a4"),
        spaceAfter=20, alignment=TA_CENTER,
    ))
    styles.add(ParagraphStyle(
        name="SectionHeader",
        fontSize=14, fontName="Helvetica-Bold",
        textColor=colors.HexColor("#667eea"),
        spaceBefore=16, spaceAfter=8,
    ))
    styles.add(ParagraphStyle(
        name="BodyText2",
        fontSize=10, fontName="Helvetica",
        textColor=colors.HexColor("#333333"),
        spaceAfter=4, leading=14,
    ))
    styles.add(ParagraphStyle(
        name="InsightCard",
        fontSize=11, fontName="Helvetica-Bold",
        textColor=colors.HexColor("#111111"),
        spaceBefore=4, spaceAfter=4,
    ))
    return styles


def _header_table_style() -> TableStyle:
    return TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#667eea")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, 0), 10),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.HexColor("#f8f9fa"), colors.white]),
        ("FONTSIZE", (0, 1), (-1, -1), 9),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#dee2e6")),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("PADDING", (0, 0), (-1, -1), 6),
    ])


# ──────────────────────────────────────────
# PDF Generation
# ──────────────────────────────────────────
def generate_pdf_report(
    title: str,
    df: pd.DataFrame,
    insights: list[dict],
    ai_summary: str = "",
    kpis: list[dict] = None,
    username: str = "User",
    user_id: int = None,
) -> tuple[bytes, str]:
    """
    Generate a complete PDF report.

    Returns:
        (pdf_bytes, file_path)
    """
    styles = _get_styles()
    story = []

    # ── Cover ──────────────────────────────
    story.append(Spacer(1, 1.5 * inch))
    story.append(Paragraph("🤖 AI Data Analyst Assistant", styles["AppTitle"]))
    story.append(Paragraph("Enterprise Analytics Report", styles["SubTitle"]))
    story.append(HRFlowable(width="100%", thickness=2, color=colors.HexColor("#667eea")))
    story.append(Spacer(1, 0.2 * inch))

    meta_data = [
        ["Report Title:", title],
        ["Generated By:", username],
        ["Date:", datetime.now().strftime("%B %d, %Y %H:%M")],
        ["Dataset Rows:", f"{len(df):,}"],
        ["Dataset Columns:", str(len(df.columns))],
    ]
    meta_table = Table(meta_data, colWidths=[2 * inch, 4.5 * inch])
    meta_table.setStyle(TableStyle([
        ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
        ("FONTNAME", (1, 0), (1, -1), "Helvetica"),
        ("FONTSIZE", (0, 0), (-1, -1), 10),
        ("TEXTCOLOR", (0, 0), (0, -1), colors.HexColor("#667eea")),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
    ]))
    story.append(meta_table)
    story.append(Spacer(1, 0.3 * inch))

    # ── KPIs ───────────────────────────────
    if kpis:
        story.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor("#dee2e6")))
        story.append(Paragraph("📊 Key Performance Indicators", styles["SectionHeader"]))
        kpi_rows = []
        row = []
        for i, kpi in enumerate(kpis[:6]):
            row.append(f"{kpi['icon']} {kpi['label']}: {kpi['value']}")
            if len(row) == 3 or i == len(kpis) - 1:
                kpi_rows.append(row[:])
                row = []
        kpi_table = Table(kpi_rows, colWidths=[2.16 * inch] * 3)
        kpi_table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#f0f4ff")),
            ("FONTNAME", (0, 0), (-1, -1), "Helvetica-Bold"),
            ("FONTSIZE", (0, 0), (-1, -1), 10),
            ("TEXTCOLOR", (0, 0), (-1, -1), colors.HexColor("#667eea")),
            ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#c8d4ff")),
            ("PADDING", (0, 0), (-1, -1), 10),
            ("ALIGN", (0, 0), (-1, -1), "CENTER"),
        ]))
        story.append(kpi_table)
        story.append(Spacer(1, 0.2 * inch))

    # ── AI Summary ─────────────────────────
    if ai_summary:
        story.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor("#dee2e6")))
        story.append(Paragraph("🧠 Executive Summary (AI Generated)", styles["SectionHeader"]))
        for para in ai_summary.split("\n"):
            if para.strip():
                text = para.strip().lstrip("#").strip()
                story.append(Paragraph(text, styles["BodyText2"]))
        story.append(Spacer(1, 0.2 * inch))

    # ── Insights ───────────────────────────
    if insights:
        story.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor("#dee2e6")))
        story.append(Paragraph("💡 Business Insights", styles["SectionHeader"]))
        
        # Create wrap-supporting styles
        ins_header_style = ParagraphStyle(
            "InsHeader", parent=styles["Normal"],
            fontSize=8, leading=10, fontName="Helvetica-Bold", textColor=colors.white
        )
        ins_cell_style = ParagraphStyle(
            "InsCell", parent=styles["Normal"],
            fontSize=8, leading=10, textColor=colors.HexColor("#333333")
        )
        
        headers = [
            Paragraph("Category", ins_header_style),
            Paragraph("Value", ins_header_style),
            Paragraph("Notes", ins_header_style),
        ]
        
        ins_rows = []
        for i in insights[:10]:
            ins_rows.append([
                Paragraph(i["icon"] + " " + i["title"], ins_cell_style),
                Paragraph(str(i["value"]), ins_cell_style),
                Paragraph(str(i["subtitle"]), ins_cell_style),
            ])
            
        ins_table = Table(
            [headers] + ins_rows,
            colWidths=[2.2 * inch, 1.8 * inch, 2.5 * inch],
        )
        ins_table.setStyle(_header_table_style())
        story.append(ins_table)
        story.append(Spacer(1, 0.3 * inch))

    # ── Data Preview ───────────────────────
    story.append(PageBreak())
    story.append(Paragraph("📋 Dataset Preview (First 8 columns, 20 rows)", styles["SectionHeader"]))
    
    # Cap columns to 8 for PDF layout readability
    max_preview_cols = 8
    preview_cols = df.columns[:max_preview_cols].tolist()
    preview_df = df[preview_cols].head(20)
    
    # Text styles for table cells to support auto-wrapping
    table_cell_style = ParagraphStyle(
        "TableCell", parent=styles["Normal"],
        fontSize=7, leading=9, textColor=colors.HexColor("#333333")
    )
    table_header_style = ParagraphStyle(
        "TableHeader", parent=styles["Normal"],
        fontSize=7.5, leading=10, fontName="Helvetica-Bold", textColor=colors.white
    )
    
    # Wrap all headers and cells in Paragraph flowables
    headers = [Paragraph(str(c), table_header_style) for c in preview_cols]
    data_rows = []
    for _, row in preview_df.iterrows():
        data_rows.append([Paragraph(str(v)[:60], table_cell_style) for v in row])
        
    # Calculate column widths to fit print boundary (6.5 inches printing page width)
    col_width = (6.5 / len(preview_cols)) * inch
    
    data_table = Table([headers] + data_rows, colWidths=[col_width] * len(preview_cols))
    data_table.setStyle(_header_table_style())
    story.append(data_table)

    # ── Footer ─────────────────────────────
    story.append(Spacer(1, 0.5 * inch))
    story.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor("#dee2e6")))
    story.append(Paragraph(
        f"Generated by AI Data Analyst Assistant • {datetime.now().strftime('%Y')}",
        ParagraphStyle("Footer", fontSize=8, textColor=colors.HexColor("#999999"), alignment=TA_CENTER)
    ))

    # ── Build PDF ──────────────────────────
    safe_title = "".join(c if c.isalnum() or c in " _-" else "_" for c in title)
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    filename = f"report_{safe_title}_{timestamp}.pdf"
    file_path = REPORTS_DIR / (str(user_id) if user_id else "shared") / filename
    file_path.parent.mkdir(parents=True, exist_ok=True)

    buf = io.BytesIO()
    doc = SimpleDocTemplate(
        buf, pagesize=A4,
        rightMargin=0.75 * inch, leftMargin=0.75 * inch,
        topMargin=0.75 * inch, bottomMargin=0.75 * inch,
    )
    doc.build(story)

    pdf_bytes = buf.getvalue()

    # Save to disk too
    with open(str(file_path), "wb") as f:
        f.write(pdf_bytes)

    return pdf_bytes, str(file_path)


# ──────────────────────────────────────────
# CSV / Excel Export
# ──────────────────────────────────────────
def export_csv(df: pd.DataFrame) -> bytes:
    """Return CSV bytes for download."""
    return df.to_csv(index=False).encode("utf-8")


def export_excel(df: pd.DataFrame, sheet_name: str = "Data") -> bytes:
    """Return Excel bytes for download."""
    buf = io.BytesIO()
    with pd.ExcelWriter(buf, engine="xlsxwriter") as writer:
        df.to_excel(writer, index=False, sheet_name=sheet_name)
        workbook = writer.book
        worksheet = writer.sheets[sheet_name]
        header_fmt = workbook.add_format({
            "bold": True, "bg_color": "#667eea",
            "font_color": "#ffffff", "border": 1,
        })
        for col_num, col_name in enumerate(df.columns):
            worksheet.write(0, col_num, col_name, header_fmt)
            col_width = max(len(str(col_name)) + 2, 12)
            worksheet.set_column(col_num, col_num, col_width)
    return buf.getvalue()
